# ===================================================================
# OpenID Connect Settings. Default settings are for Keycloak in Docker.
# Start Keycloak using `docker-compose -f src/main/docker/keycloak.yml up`.
#
# To use Okta, your settings should resemble the following:
#
# accessTokenUri: https://{yourOktaDomain}.com/oauth2/default/v1/token
# userAuthorizationUri: https://{yourOktaDomain}.com/oauth2/default/v1/authorize
# clientId: {copy after creating an OIDC app}
# clientSecret: {copy after creating an OIDC app}
# userInfoUri: https://{yourOktaDomain}.com/oauth2/default/v1/userinfo
# tokenInfoUri: https://{yourOktaDomain}.com/oauth2/default/v1/introspect
#
# You can also override these properties using environment variables.
# For example:
#
# export SECURITY_OAUTH2_CLIENT_CLIENT_ID="jhipster"
# export SECURITY_OAUTH2_CLIENT_CLIENT_SECRET="38561a05"
# ===================================================================
security:
    basic:
        enabled: false
    oauth2:
        client:
            access-token-uri: http://oauth.spoc.ccnu.edu.cn/oauth/token
            user-authorization-uri: http://oauth.spoc.ccnu.edu.cn/oauth/authorize
            client-id: starmooc-registry
            client-secret: starmooc-registry-secret
            client-authentication-scheme: form
            scope: read
        resource:
            user-info-uri: http://oauth.spoc.ccnu.edu.cn/user_info
            token-info-uri: http://oauth.spoc.ccnu.edu.cn/oauth/token
            prefer-token-info: false

server:
    session:
        cookie:
            http-only: true
